apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    router.deis.cc/routable: "true"
    app: nginx
  annotations:
    router.deis.cc/domains: nginx
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
